### ISSUE TITLE
StimuliId parsing

### ISSUE THREAD

**Issue by alexdean201** [SmarterApp/TabulateSmarterTestAdminPackage#19]
**Environment**
admin tabulator version: 2.2.0

**Steps to Reproduce**
1. Run admin tabulator with only the -i and -o parameters
2. Open and observe the StimuliId column in the stim CSV file

**Expected**
The value of the stim id

**Actual**
The bank key
![stimuli_parsing_error](https://user-images.githubusercontent.com/15095616/28226739-0f91c25a-688c-11e7-9014-698480c6a962.png)

**Comment by alexdean201** [comment]
In StimuliTabulator.cs, it looks like the stimuliid is being parsed to the first occurance of a hypen. Since the full stim name is _stim-bankkey-stimid_, the parsing will need to be done on the second hypen.

**Comment by alexdean201** [comment]
Also, this has an effect on running the tabulator with the -cs or -ci parameters, as the app is unable to find the correct stimuli.

**Comment by hbgwhite** [comment]
This issue is solved in version 2.2.2
