### ISSUE TITLE
Issues parsing IRT parameter for ELA WER item type

### ISSUE THREAD

**Issue by upretip** [SmarterApp/TabulateSmarterTestAdminPackage#25]
@bredd  -- the following issue is raised by Matt Schulz. He is worried that the item parameters are not parsed correctly for WER items.

According to Matt-

`The issue affects only WER items, which are represented by two sets of item parameters in the test package.   The following screen shot captures the two sets of item statistics as they are found in the test package for one item, ID 54155 (Grade 11 ELA):`
 
![image](https://user-images.githubusercontent.com/13579394/40859364-5d1bbabe-6596-11e8-9b7a-62d44238eb3c.png)
 
`And the following screen shot shows the item statistics that are found for this item in the admin tabulator item output file.  The problem is that there is only one record for this item and it contains a mixture of the parameters of the C- and D-dimension items. `
 
![image](https://user-images.githubusercontent.com/13579394/40859379-6d8da3e4-6596-11e8-8ad5-28c16677a653.png)

`_Until this issue is resolved, we can only partially QC the parameters of WER items in the test packages._`

He is expecting separate sets of parameters for Dimension C and Dimension D WER items.

**Comment by upretip** [comment]
Any update on this @alexdean201 ?

**Comment by alexdean201** [comment]
@upretip, I'm looking into it now

**Comment by alexdean201** [comment]
@upretip I released a [v2.2.4-beta version](https://github.com/SmarterApp/TabulateSmarterTestAdminPackage/releases/tag/v2.2.4-beta) that reports on the multiple parameters for Dimension C and Dimension D WER items.
